/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ParentJNI */

#ifndef _Included_ParentJNI
#define _Included_ParentJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ParentJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ParentJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
