/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "VersionChecker_constants.h"

namespace VersionChecker {

const VersionCheckerConstants g_VersionChecker_constants;

VersionCheckerConstants::VersionCheckerConstants() {
}

} // namespace

