/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef VersionChecker_CONSTANTS_H
#define VersionChecker_CONSTANTS_H

#include "VersionChecker_types.h"

namespace VersionChecker {

class VersionCheckerConstants {
 public:
  VersionCheckerConstants();

};

extern const VersionCheckerConstants g_VersionChecker_constants;

} // namespace

#endif
