// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "VersionChecker.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::VersionChecker;

class VersionCheckerHandler : virtual public VersionCheckerIf {
 public:
  VersionCheckerHandler() {
    // Your initialization goes here
  }

  void fetchVersion(Version& _return, const Version& ver) {
    // Your implementation goes here
    printf("fetchVersion\n");
  }

  void getFile() {
    // Your implementation goes here
    printf("getFile\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::apache::thrift::stdcxx::shared_ptr<VersionCheckerHandler> handler(new VersionCheckerHandler());
  ::apache::thrift::stdcxx::shared_ptr<TProcessor> processor(new VersionCheckerProcessor(handler));
  ::apache::thrift::stdcxx::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::apache::thrift::stdcxx::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::apache::thrift::stdcxx::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

